function [Times,Channel1,Channel3,Channel4,Channel6,Channel7,Channel8,Channel9,Channel10,Channel11] = importEmgTextFile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIMES,RTTIBANTUV,RTMEDGASTROUV,RTLATGASTROUV,RTBICEPSFEMUV,RTVMOUV,RTVLOUV,RTRECTUSFEMUV,RTSOLEUSUV,RTSEMITENDUV]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIMES,RTTIBANTUV,RTMEDGASTROUV,RTLATGASTROUV,RTBICEPSFEMUV,RTVMOUV,RTVLOUV,RTRECTUSFEMUV,RTSOLEUSUV,RTSEMITENDUV]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Times,RTTIBANTuV,RTMEDGASTROuV,RTLATGASTROuV,RTBICEPSFEMuV,RTVMOuV,RTVLOuV,RTRECTUSFEMuV,RTSOLEUSuV,RTSEMITENDuV]
%   = importfile('CORE15_slow.txt',6, 45005);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/02/16 12:08:32

%% Initialize variables.
delimiter = '\t';
if nargin<=2
     startRow = 6;
     endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
     frewind(fileID);
     dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
     for col=1:length(dataArray)
          dataArray{col} = [dataArray{col};dataArrayBlock{col}];
     end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Times = dataArray{:, 1};
Channel1 = dataArray{:, 2};
Channel3 = dataArray{:, 3};
Channel4 = dataArray{:, 4};
Channel6 = dataArray{:, 5};
Channel7 = dataArray{:, 6};
Channel8 = dataArray{:, 7};
Channel9 = dataArray{:, 8};
Channel10 = dataArray{:, 9};
Channel11 = dataArray{:, 10};

