function [Frames1,SubFrame1,Channel3,Frame1] = ImportEMG(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as column vectors.
%   [FRAMES1,SUBFRAME1,CHANNEL3,FRAME1] = IMPORTFILE1(FILENAME) Reads data
%   from text file FILENAME for the default selection.
%
%   [FRAMES1,SUBFRAME1,CHANNEL3,FRAME1] = IMPORTFILE1(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [Frames1,SubFrame1,Channel3,Frame1] =
%   importfile1('slowWalk_NoisyEMG.csv',6, 3085);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/07/22 11:06:39

%% Initialize variables.
delimiter = ',';
if nargin<=2
     startRow = 6;
     endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
     frewind(fileID);
     dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
     for col=1:length(dataArray)
          dataArray{col} = [dataArray{col};dataArrayBlock{col}];
     end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Frames1 = dataArray{:, 1};
SubFrame1 = dataArray{:, 2};
Channel3 = dataArray{:, 3};
Frame1 = dataArray{:, 4};

