%% Goncalves,BM (2018)
% Convert data in .Dat to Mat format.
%
%
% CALLBACK FUNCTIONS
%
%       DatText (Auto-generated by MATLAB)
%       DatRawData (Auto-generated by MATLAB)
%
%   OUTPUT
%       Creates folder "ElaboratedData" with subfolder "sessionData" in the
%       original participant folder. 

function []= dat2mat(DatFolder)
%% find the folder of the subject to analyse
if nargin ==0                        %if DatFolder does not exists
DatFolder = uigetdir('Name','select the folder with the .dat files');
end
cd(DatFolder);
Files = dir([DatFolder filesep '*.dat']);               % select the files that are .dat
%% delete all names that do not contain '.dat'
DeletedFiles =0;
Numbers = '0123456789';                                 % use to verify if name of the trial contains a number

for i = 1: length (Files)                               % run trhough all the files
    n = i-DeletedFiles;                                 % use variable to account for deleted files
    contNum = 0;                                        % LOGICAL to check if contains number
    if contains (Files(n).name,'.dat') ~= 1             % check if DOES NOT contains '.dat'
        Files(n)=[];                                    % IF YES delete row
        DeletedFiles = DeletedFiles +1;
    end
end

%% Get the Number of files and subject name

Nfiles = length(Files);                                                     % get the number of files

% get the code of the subject
lastDash = strfind(Files(1).folder,'\');                                    % find all the backslashes in the name of the folder
lastDash = lastDash (end);                                                  % get the last backslash, prior to the folder name
subject = Files(1).folder (lastDash+1:end);                                 % get the subject's code

clear lastDash
%% Check if ElaboratedData and sessionData folder exist
if  exist ('ElaboratedData')==0                                                        % if the folder "ElaboratedData" does not exist
    mkdir ('ElaboratedData');                                                          % create a new folder for ElaboratedData
    ElabFolder = sprintf('%s\\ElaboratedData',DatFolder);                              % directory for the new folder
    cd (ElabFolder);
    mkdir('sessionData');
end
ElabFolder = sprintf('%s\\ElaboratedData',DatFolder);                              % directory for the new folder
SessionFolder = sprintf('%s\\sessionData',ElabFolder);

cd (SessionFolder);
LoadBar = waitbar(0,'Please wait...');

%% loop through all the files in the folder containing the '.dat' files

for trial = 1: Nfiles                                                       
    %
    waitbar(trial/Nfiles,LoadBar,'Please wait...');
    cd (SessionFolder);
    filename =Files (trial).name;
 
    
    FileFolder =  filename (1:end-4);                                           % remove ".dat" from the filename
    FileFolderDirSave = sprintf('%s\\%s\\AnalogData',SessionFolder,FileFolder);
    
    if  exist (FileFolder)~=7                                                    % if the folder "MatData" does not exist
        mkdir (FileFolder);                                                          % create a new folder for MatData
    end

      
    %% Output Data

    cd (DatFolder);
    Text = DatText (filename);                                  % get data from the DatFile as text
    [numRows,numCol]=size(Text);
    
    idxTime = find (contains (Text,'Time'));                    % find the cell that contains the word "Time"                
    
    Labels = Text (idxTime,:);
    MetaData = Text (1:idxTime-1,:);
    RawData = DatRawData (filename);
    
    idxRate = find (contains (Text,'Rate'));
    AnalogData.Rate = str2double(MetaData (idxRate,2));                     % Sampling Rate
    AnalogData.Labels = cellstr(Labels);                                    % lables of each Channel
    AnalogData.RawData = RawData;                                           % Raw Data
   
    %% Save output in the new folder
    
    save (FileFolderDirSave, 'AnalogData')
    
    cd (DatFolder);
        
end

close (LoadBar);

msgbox('.dat files converted to MAT')

